apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-virtual-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: k8s-virtual-device-plugin
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: k8s-virtual-device-plugin
    spec:
      tolerations:
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: dtaniwaki/k8s-virtual-device-plugin:latest
        imagePullPolicy: IfNotPresent
        name: k8s-virtual-device-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: config
          mountPath: /etc/k8s-virtual-device-plugin
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: config
        configMap:
          name: virtual-device
          items:
          - key: device.yaml
            path: device.yaml
