language: go
go:
- "1.15.x"

go_import_path: github.com/dtaniwaki/k8s-virtual-device-plugin

env:
- GO111MODULE=on

install:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint
- go install github.com/mattn/goveralls

before_script: make lint

script:
- make test coverage

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
